### ISSUE TITLE
[BUG] core无法启动，日志未见错误

### ISSUE THREAD

**Issue by bigguyong** [morytyann/OpenWrt-mihomo#155]
### 自查步骤

- [X] OpenWrt 23及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建插件，而不是其他Fork
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题

### 系统

ImmortalWrt

### 系统版本

ImmortalWrt 23.05.3 r27917-81a1f98d5b 

### 插件版本

1.7.6

### 硬件架构

x86_64

### BUG 描述

Core Status : Not Running

### 预期行为

core能够启动成功

### 复现步骤

无特殊操作，始终无法启动 

### 插件配置

1

### 配置文件

```
port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
ipv6: false
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [180.184.1.1, 119.29.29.29]
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://1.12.12.12/dns-query', 'https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies:
    - { ... }
proxy-groups:
    - { name: '🚀 节点选择', type: select, proxies: ['🔯 故障转移', '🎯 自动选择', '香港 01', '香港 02', '香港 03', '新加坡 01', '新加坡 02', '新加坡 03', '台湾 01', '台湾 02', '台湾 03', '美国 01', '美国 02', '美国 03', '日本 01', '日本 02', '日本 03', 'IPLC(HW) 香港HKT家宽', 'IPLC(HW) 新加坡', 'IPLC(HW) 日本Sonet家宽', 'IPLC(HW) 美国ATT家宽', 'IPLC(HW) 台湾', 'Base 韩国SKT家宽', 'Base 美国Frontier家宽', 'Base 马来西亚TMNet家宽', 'Base 马来西亚', 'Base 泰国', 'Base 越南', 'Base 印度尼西亚', 'Base 澳大利亚 悉尼', 'Base 菲律宾 01', 'Base 菲律宾 02', 'Base 印度', 'Base 新西兰', 'Base 阿根廷', 'Base 尼日利亚', 'Base 瑞典', 'Base 意大利', 'Base 巴西', 'Base 英国', 'Base 土耳其', 'Base 德国', 'Base 巴基斯坦', 'Base 芬兰', 'Base 加拿大', 'Base 哈萨克斯坦', 'Base 乌拉圭', 'Plus 广港 Game 限速5M', 'Plus 沪日 Game 限速5M', 'Plus 沪韩 Game 限速5M'] }
    - { name: '📹 Youtube', type: select, proxies: ['🇭🇰 香港节点', '🇸🇬 新加坡节点', '🇺🇸 美国节点', '🌎 其他国家'] }
    - { name: '🎥 Netflix', type: select, proxies: ['🇭🇰 香港节点', '🇸🇬 新加坡节点', '🇺🇸 美国节点', '🌎 其他国家'] }
    - { name: '🖥️ ChatGPT/NewBing', type: select, proxies: ['🇺🇸 美国节点', '🇸🇬 新加坡节点', '🌎 其他国家'] }
    - { name: '🇭🇰 香港节点', type: select, proxies: ['香港 01', '香港 02', '香港 03', 'IPLC(HW) 香港HKT家宽'] }
    - { name: '🇸🇬 新加坡节点', type: select, proxies: ['新加坡 01', '新加坡 02', '新加坡 03', 'IPLC(HW) 新加坡'] }
    - { name: '🇺🇸 美国节点', type: select, proxies: ['美国 01', '美国 02', '美国 03', 'IPLC(HW) 美国ATT家宽', 'Base 美国Frontier家宽'] }
    - { name: '🌎 其他国家', type: select, proxies: ['台湾 01', '台湾 02', '台湾 03', '日本 01', '日本 02', '日本 03', 'IPLC(HW) 日本Sonet家宽', 'IPLC(HW) 台湾', 'Base 韩国SKT家宽', 'Base 马来西亚TMNet家宽', 'Base 马来西亚', 'Base 泰国', 'Base 越南', 'Base 印度尼西亚', 'Base 澳大利亚 悉尼', 'Base 菲律宾 01', 'Base 菲律宾 02', 'Base 印度', 'Base 新西兰', 'Base 阿根廷', 'Base 尼日利亚', 'Base 瑞典', 'Base 意大利', 'Base 巴西', 'Base 英国', 'Base 土耳其', 'Base 德国', 'Base 巴基斯坦', 'Base 芬兰', 'Base 加拿大', 'Base 哈萨克斯坦', 'Base 乌拉圭', 'Plus 广港 Game 限速5M', 'Plus 沪日 Game 限速5M', 'Plus 沪韩 Game 限速5M'] }
    - { name: '🎯 自动选择', type: url-test, proxies: ['香港 01', '香港 02', '香港 03', '新加坡 01', '新加坡 02', '新加坡 03', '台湾 01', '台湾 02', '台湾 03', '美国 01', '美国 02', '美国 03', '日本 01', '日本 02', '日本 03', 'IPLC(HW) 香港HKT家宽', 'IPLC(HW) 新加坡', 'IPLC(HW) 日本Sonet家宽', 'IPLC(HW) 美国ATT家宽', 'IPLC(HW) 台湾', 'Base 韩国SKT家宽', 'Base 美国Frontier家宽', 'Base 马来西亚TMNet家宽', 'Base 马来西亚', 'Base 泰国', 'Base 越南', 'Base 印度尼西亚', 'Base 澳大利亚 悉尼', 'Base 菲律宾 01', 'Base 菲律宾 02', 'Base 印度', 'Base 新西兰', 'Base 阿根廷', 'Base 尼日利亚', 'Base 瑞典', 'Base 意大利', 'Base 巴西', 'Base 英国', 'Base 土耳其', 'Base 德国', 'Base 巴基斯坦', 'Base 芬兰', 'Base 加拿大', 'Base 哈萨克斯坦', 'Base 乌拉圭'], url: 'http://www.gstatic.com/generate_204', interval: 86400 }
    - { name: '🔯 故障转移', type: fallback, proxies: ['香港 01', '香港 02', '香港 03', '新加坡 01', '新加坡 02', '新加坡 03', '台湾 01', '台湾 02', '台湾 03', '美国 01', '美国 02', '美国 03', '日本 01', '日本 02', '日本 03', 'IPLC(HW) 香港HKT家宽', 'IPLC(HW) 新加坡', 'IPLC(HW) 日本Sonet家宽', 'IPLC(HW) 美国ATT家宽', 'IPLC(HW) 台湾', 'Base 韩国SKT家宽', 'Base 美国Frontier家宽', 'Base 马来西亚TMNet家宽', 'Base 马来西亚', 'Base 泰国', 'Base 越南', 'Base 印度尼西亚', 'Base 澳大利亚 悉尼', 'Base 菲律宾 01', 'Base 菲律宾 02', 'Base 印度', 'Base 新西兰', 'Base 阿根廷', 'Base 尼日利亚', 'Base 瑞典', 'Base 意大利', 'Base 巴西', 'Base 英国', 'Base 土耳其', 'Base 德国', 'Base 巴基斯坦', 'Base 芬兰', 'Base 加拿大', 'Base 哈萨克斯坦', 'Base 乌拉圭', 'Plus 广港 Game 限速5M', 'Plus 沪日 Game 限速5M', 'Plus 沪韩 Game 限速5M'], url: 'http://www.gstatic.com/generate_204', interval: 7200 }
rules:
    - 'DOMAIN,sub.getlitchi.com,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,🚀 节点选择'
```

### 插件日志

[2024-09-02 16:48:44] App is enabled.
[2024-09-02 16:48:44] Starting...
[2024-09-02 16:48:48] Use Subscription: ENET
[2024-09-02 16:48:48] Mixin is enabled, mixin all config.
[2024-09-02 16:48:49] Profile testing...
[2024-09-02 16:48:49] Profile test passed!
[2024-09-02 16:48:49] Start Core
[2024-09-02 16:48:49] Transparent Proxy is enabled.
[2024-09-02 16:48:49] Transparent Proxy: Start hijack.
[2024-09-02 16:48:49] Transparent Proxy: Using TUN mode.
[2024-09-02 16:48:49] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-09-02 16:48:49] Transparent Proxy: IPv6 DNS Hijack is enabled, IPv6 dns request will redirect to the core.
[2024-09-02 16:48:49] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-09-02 16:48:50] Transparent Proxy: Destination TCP Port to Proxy: 1-65535.
[2024-09-02 16:48:50] Transparent Proxy: Destination UDP Port to Proxy: 1-65535.
[2024-09-02 16:48:50] Transparent Proxy: Add exclusions.
[2024-09-02 16:48:50] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-09-02 16:48:50] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-09-02 16:48:50] Transparent Proxy: Access Control is using all mode, set proxy for all client.
[2024-09-02 16:48:50] Start Successful!

### 核心日志

time="2024-09-02T16:48:49.891387118+08:00" level=info msg="Start initial configuration in progress"
time="2024-09-02T16:48:49.894847264+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-09-02T16:48:49.894951073+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-09-02T16:48:49.89782033+08:00" level=info msg="Load GeoIP rule: cn"
time="2024-09-02T16:48:49.915288144+08:00" level=info msg="Finished initial GeoIP rule cn => DIRECT, records: 7461"
time="2024-09-02T16:48:49.915864035+08:00" level=info msg="Finished initial GeoIP rule cn => dns.fallback-filter.geoip, records: 7461"
time="2024-09-02T16:48:49.915980431+08:00" level=info msg="Initial configuration complete, total time: 24ms"
configuration file /etc/mihomo/run/config.yaml test is successful

### 附加信息

1
