### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dead-Universe** [morytyann/OpenWrt-mihomo#167]
### 自查步骤

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、节点信息等敏感信息

### 系统

OpenWrt

### 系统版本

23.05-SNAPSHOT

### 插件版本

git-25.245.45304-dc2926e

### 硬件架构

arm_cortex-a5_vfpv4

### BUG 描述

在使用[chatgpt](https://chatgpt.com/)时会出现[请求](https://chatgpt.com/backend-api/conversation)的EventStream未完成的情况，表现为输出到一半就停止了。

### 预期行为

完成响应

### 复现步骤

打开[chatgpt](https://chatgpt.com/)进行聊天

### 插件配置

```txt
mihomo.status=status
mihomo.config=config
mihomo.config.enabled='1'
mihomo.config.scheduled_restart='0'
mihomo.config.cron_expression='0 3 * * *'
mihomo.config.profile='file:iKuuu_V2.yaml'
mihomo.config.mixin='1'
mihomo.config.test_profile='1'
mihomo.config.upload_profile='/etc/mihomo/profiles/iKuuu_V2.yaml'
mihomo.config.fast_reload='1'
mihomo.proxy=proxy
mihomo.proxy.transparent_proxy='1'
mihomo.proxy.transparent_proxy_mode='tproxy'
mihomo.proxy.ipv4_dns_hijack='1'
mihomo.proxy.ipv6_dns_hijack='0'
mihomo.proxy.ipv4_proxy='1'
mihomo.proxy.ipv6_proxy='0'
mihomo.proxy.router_proxy='1'
mihomo.proxy.lan_proxy='1'
mihomo.proxy.access_control_mode='all'
mihomo.proxy.bypass_china_mainland_ip='1'
mihomo.proxy.acl_tcp_dport='1-65535'
mihomo.proxy.acl_udp_dport='1-65535'
mihomo.proxy.wan_interfaces='wan' 'wwan'
mihomo.proxy.wan6_interfaces='wwan'
mihomo.mixin=mixin
mihomo.mixin.mode='rule'
mihomo.mixin.match_process='off'
mihomo.mixin.unify_delay='1'
mihomo.mixin.tcp_concurrent='1'
mihomo.mixin.tcp_keep_alive_interval='600'
mihomo.mixin.log_level='info'
mihomo.mixin.ui_name='metacubexd'
mihomo.mixin.ui_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
mihomo.mixin.api_port='9090'
mihomo.mixin.selection_cache='1'
mihomo.mixin.allow_lan='1'
mihomo.mixin.http_port='8080'
mihomo.mixin.socks_port='1080'
mihomo.mixin.mixed_port='7890'
mihomo.mixin.redir_port='7891'
mihomo.mixin.tproxy_port='7892'
mihomo.mixin.authentication='0'
mihomo.mixin.tun_stack='system'
mihomo.mixin.tun_mtu='9000'
mihomo.mixin.tun_gso='1'
mihomo.mixin.tun_gso_max_size='65536'
mihomo.mixin.tun_endpoint_independent_nat='0'
mihomo.mixin.dns_port='1053'
mihomo.mixin.dns_mode='redir-host'
mihomo.mixin.fake_ip_range='198.18.0.1/16'
mihomo.mixin.fake_ip_filter='0'
mihomo.mixin.fake_ip_filters='+.lan' '+.local'
mihomo.mixin.fake_ip_cache='0'
mihomo.mixin.dns_ipv6='0'
mihomo.mixin.dns_system_hosts='0'
mihomo.mixin.dns_hosts='0'
mihomo.mixin.hosts='0'
mihomo.mixin.dns_nameserver='0'
mihomo.mixin.dns_fallback_filter='0'
mihomo.mixin.dns_nameserver_policy='0'
mihomo.mixin.sniffer='0'
mihomo.mixin.sniff_dns_mapping='1'
mihomo.mixin.sniff_pure_ip='1'
mihomo.mixin.sniffer_overwrite_dest='1'
mihomo.mixin.geoip_format='dat'
mihomo.mixin.geodata_loader='memconservative'
mihomo.mixin.geosite_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
mihomo.mixin.geoip_mmdb_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
mihomo.mixin.geoip_dat_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
mihomo.mixin.geoip_asn_url='https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb'
mihomo.mixin.geox_auto_update='1'
mihomo.mixin.geox_update_interval='24'
mihomo.mixin.api_secret='267437'
mihomo.mixin.ipv6='0'
mihomo.@authentication[0]=authentication
mihomo.@authentication[0].enabled='1'
mihomo.@authentication[0].username='mihomo'
mihomo.@authentication[0].password='267437'
mihomo.@host[0]=host
mihomo.@host[0].enabled='0'
mihomo.@host[0].domain_name='localhost'
mihomo.@host[0].ip='127.0.0.1' '::1'
mihomo.@nameserver[0]=nameserver
mihomo.@nameserver[0].enabled='1'
mihomo.@nameserver[0].type='default-nameserver'
mihomo.@nameserver[0].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[1]=nameserver
mihomo.@nameserver[1].enabled='1'
mihomo.@nameserver[1].type='proxy-server-nameserver'
mihomo.@nameserver[1].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[2]=nameserver
mihomo.@nameserver[2].enabled='1'
mihomo.@nameserver[2].type='nameserver'
mihomo.@nameserver[2].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[3]=nameserver
mihomo.@nameserver[3].enabled='1'
mihomo.@nameserver[3].type='fallback'
mihomo.@nameserver[3].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.@fallback_filter[0]=fallback_filter
mihomo.@fallback_filter[0].enabled='1'
mihomo.@fallback_filter[0].type='geoip-code'
mihomo.@fallback_filter[0].value='CN'
mihomo.@fallback_filter[1]=fallback_filter
mihomo.@fallback_filter[1].enabled='1'
mihomo.@fallback_filter[1].type='geosite'
mihomo.@fallback_filter[1].value='GFW'
mihomo.@fallback_filter[2]=fallback_filter
mihomo.@fallback_filter[2].enabled='0'
mihomo.@fallback_filter[2].type='ipcidr'
mihomo.@fallback_filter[3]=fallback_filter
mihomo.@fallback_filter[3].enabled='0'
mihomo.@fallback_filter[3].type='domain_name'
mihomo.@nameserver_policy[0]=nameserver_policy
mihomo.@nameserver_policy[0].enabled='1'
mihomo.@nameserver_policy[0].matcher='geosite:cn,private'
mihomo.@nameserver_policy[0].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver_policy[1]=nameserver_policy
mihomo.@nameserver_policy[1].enabled='1'
mihomo.@nameserver_policy[1].matcher='geosite:geolocation-!cn'
mihomo.@nameserver_policy[1].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.@sniff[0]=sniff
mihomo.@sniff[0].enabled='1'
mihomo.@sniff[0].protocol='HTTP'
mihomo.@sniff[0].port='80' '8080-8880'
mihomo.@sniff[0].overwrite_dest='1'
mihomo.@sniff[1]=sniff
mihomo.@sniff[1].enabled='1'
mihomo.@sniff[1].protocol='TLS'
mihomo.@sniff[1].port='443' '8443'
mihomo.@sniff[1].overwrite_dest='1'
mihomo.@sniff[2]=sniff
mihomo.@sniff[2].enabled='1'
mihomo.@sniff[2].protocol='QUIC'
mihomo.@sniff[2].port='443' '8443'
mihomo.@sniff[2].overwrite_dest='1'
mihomo.editor=editor
mihomo.log=log
```

### 配置文件

```yaml
port: 8080
socks-port: 1080
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
hosts:
  time.facebook.com: 17.253.84.125
  time.android.com: 17.253.84.125
dns:
  enable: true
  use-hosts: false
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://223.5.5.5
    - tcp://223.6.6.6
    - tls://dns.google:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://dns.alidns.com
    - tls://223.5.5.5
    - tls://223.6.6.6
    - tls://dot.pub
    - tls://1.12.12.12
    - tls://120.53.53.53
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
    - tcp://119.29.29.29
    - tcp://223.5.5.5
    - tcp://223.6.6.6
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  ipv6: false
  use-system-hosts: false
proxies:
  - ..
find-process-mode: off
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 600
ipv6: false
external-ui: ui
external-ui-name: metacubexd
external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
secret: 267437
profile:
  store-selected: true
  store-fake-ip: false
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
tun:
  stack: system
  device: tun
  mtu: 9000
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: false
  enable: false
sniffer:
  enable: false
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
geodata-mode: true
geodata-loader: memconservative
geox-url:
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 24
```

### 插件日志

```txt
[2024-09-05 17:06:14] App is enabled.
[2024-09-05 17:06:14] Starting...
[2024-09-05 17:06:14] Use Profile: iKuuu_V2.yaml
[2024-09-05 17:06:14] Mixin is enabled, mixin all config.
[2024-09-05 17:06:17] Profile testing...
[2024-09-05 17:06:17] Profile test passed!
[2024-09-05 17:06:17] Start Core
[2024-09-05 17:06:17] Transparent Proxy is enabled.
[2024-09-05 17:06:17] Transparent Proxy: Start hijack.
[2024-09-05 17:06:17] Transparent Proxy: Using TPROXY mode.
[2024-09-05 17:06:17] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-09-05 17:06:17] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-09-05 17:06:17] Transparent Proxy: Bypass china mainland ip is enabled.
[2024-09-05 17:06:17] Transparent Proxy: Destination TCP Port to Proxy: 1-65535.
[2024-09-05 17:06:17] Transparent Proxy: Destination UDP Port to Proxy: 1-65535.
[2024-09-05 17:06:18] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-09-05 17:06:18] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-09-05 17:06:18] Transparent Proxy: Access Control is using all mode, set proxy for all client.
[2024-09-05 17:06:18] Start Successful!
```

### 核心日志

```txt
time="2024-09-05T17:06:17.193773755+08:00" level=info msg="Start initial configuration in progress"
time="2024-09-05T17:06:17.20277676+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-09-05T17:06:17.20288908+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-09-05T17:06:17.249837221+08:00" level=info msg="Load GeoIP rule: cn"
time="2024-09-05T17:06:17.290471787+08:00" level=info msg="Finished initial GeoIP rule cn => 🇨🇳 国内网站, records: 7461"
time="2024-09-05T17:06:17.291285223+08:00" level=info msg="Initial configuration complete, total time: 97ms"
configuration file /etc/mihomo/run/config.yaml test is successful
time="2024-09-05T17:06:18.245317113+08:00" level=info msg="Start initial configuration in progress"
time="2024-09-05T17:06:18.253604121+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-09-05T17:06:18.253717321+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-09-05T17:06:18.296559878+08:00" level=info msg="Finished initial GeoIP rule cn => 🇨🇳 国内网站, records: 7461"
time="2024-09-05T17:06:18.297185236+08:00" level=info msg="Initial configuration complete, total time: 51ms"
time="2024-09-05T17:06:18.297424675+08:00" level=error msg="External controller listen error: listen tcp 0.0.0.0:9090: bind: address already in use"
time="2024-09-05T17:06:18.297636754+08:00" level=info msg="Sniffer is closed"
time="2024-09-05T17:06:18.297676914+08:00" level=info msg="Use tcp concurrent"
time="2024-09-05T17:06:18.326624884+08:00" level=info msg="Start initial Compatible provider 🎮 Steam 登录/下载"
time="2024-09-05T17:06:18.326766563+08:00" level=info msg="Start initial Compatible provider 🔰 选择节点"
time="2024-09-05T17:06:18.326813843+08:00" level=info msg="Start initial Compatible provider 🌏 爱奇艺&哔哩哔哩"
time="2024-09-05T17:06:18.326855043+08:00" level=info msg="Start initial Compatible provider 🛑 拦截广告"
time="2024-09-05T17:06:18.326896882+08:00" level=info msg="Start initial Compatible provider 🎮 Steam 商店/社区"
time="2024-09-05T17:06:18.326936082+08:00" level=info msg="Start initial Compatible provider 📺 动画疯"
time="2024-09-05T17:06:18.326976402+08:00" level=info msg="Start initial Compatible provider 🇨🇳 国内网站"
time="2024-09-05T17:06:18.327016962+08:00" level=info msg="Start initial Compatible provider 🐟 漏网之鱼"
time="2024-09-05T17:06:18.327058562+08:00" level=info msg="Start initial Compatible provider default"
time="2024-09-05T17:06:18.327095682+08:00" level=info msg="Start initial Compatible provider ☁️ OneDrive"
time="2024-09-05T17:06:18.327135682+08:00" level=info msg="Start initial Compatible provider 🌩️ Cloudflare"
time="2024-09-05T17:06:18.327400001+08:00" level=info msg="UI already exists"
time="2024-09-05T17:06:33.847287825+08:00" level=info msg="[TCP] 192.168.111.74:51072 --> chatgpt.com:443 match IPCIDR(179.60.192.0/22) using 🔰 选择节点[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:06:33.848092302+08:00" level=info msg="[TCP] 192.168.111.74:51073 --> edge.microsoft.com:443 match DomainKeyword(.) using 🐟 漏网之鱼[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:06:33.965768256+08:00" level=info msg="[TCP] 192.168.111.83:43188 --> connectivity-check.ubuntu.com:80 match DomainKeyword(.) using 🐟 漏网之鱼[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:06:34.646387753+08:00" level=info msg="[TCP] 192.168.111.74:51076 --> chatgpt.com:443 match IPCIDR(179.60.192.0/22) using 🔰 选择节点[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:06:35.989847456+08:00" level=info msg="[TCP] 192.168.111.74:51081 --> ab.chatgpt.com:443 match DomainSuffix(chatgpt.com) using 🔰 选择节点[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:06:43.537628764+08:00" level=info msg="[TCP] 192.168.111.74:51097 --> wiki.metacubex.one:443 match DomainKeyword(.) using 🐟 漏网之鱼[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:06:43.547702566+08:00" level=info msg="[TCP] 192.168.111.74:51098 --> wiki.metacubex.one:443 match DomainKeyword(.) using 🐟 漏网之鱼[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:06:45.829269364+08:00" level=info msg="[TCP] 192.168.111.74:51102 --> unpkg.com:443 match 
time="2024-09-05T17:22:02.112651173+08:00" level=info msg="[TCP] 192.168.111.74:52857 --> edge.microsoft.com:443 match DomainKeyword(.) using 🐟 漏网之鱼[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:22:05.785678596+08:00" level=info msg="[TCP] 192.168.111.74:52863 --> openwrt.ai:443 match DomainKeyword(.) using 🐟 漏网之鱼[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:22:09.256236104+08:00" level=info msg="[TCP] 192.168.111.74:52873 --> api.github.com:443 match DomainKeyword(github) using 🔰 选择节点[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:22:11.03930745+08:00" level=info msg="[TCP] 192.168.111.74:52880 --> chatgpt.com:443 match DomainSuffix(chatgpt.com) using 🔰 选择节点[🇯🇵 日本A05 | 下载专用 | x0.01]"
time="2024-09-05T17:22:11.145354353+08:00" level=info msg="[UDP] 192.168.111.74:54639 --> cdn.oaistatic.com:443 match 
```

### 附加信息

使用平台：由[此](https://openwrt.ai/)构建的Xiaomi Redmi Router AX6S固件
使用方式：路由器作为旁路由，windows设置网关和DNS指向该路由器，其余网页正常显示，只有用
text/event-stream协议的请求会出现这个问题，在本机使用clash代理的情况下未出现该问题。
