### ISSUE TITLE
[BUG] 部分国外网站无法访问

### ISSUE THREAD

**Issue by YangZxi** [morytyann/OpenWrt-mihomo#243]
### 自查

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

OpenWrt

### 系统版本

6.6.56

### 插件版本

git-25.284.45216-8031448

### 硬件架构

arm_cortex-a8_vfpv3

### BUG 描述

1. 开启了 ipv6
2. ipv6 代理开与不开效果一样
3. tun 模式
4. dns 为 redir-host，没开 ipv6 解析

<img width="477" alt="image" src="https://github.com/user-attachments/assets/8f9ec802-4aef-46f0-9bf2-2f807bbc34db">
<img width="393" alt="image" src="https://github.com/user-attachments/assets/ce9a5c8e-86e5-4dab-875f-51a1824d3931">

### 预期行为

无

### 复现步骤

无

### 插件配置

```
mihomo.status=status
mihomo.config=config
mihomo.config.enabled='1'
mihomo.config.scheduled_restart='0'
mihomo.config.cron_expression='0 3 * * *'
mihomo.config.profile='file:mihomo.yaml'
mihomo.config.mixin='1'
mihomo.config.test_profile='1'
mihomo.config.fast_reload='1'
mihomo.proxy=proxy
mihomo.proxy.transparent_proxy='1'
mihomo.proxy.tcp_transparent_proxy_mode='tun'
mihomo.proxy.udp_transparent_proxy_mode='tun'
mihomo.proxy.ipv4_dns_hijack='1'
mihomo.proxy.ipv6_dns_hijack='1'
mihomo.proxy.ipv4_proxy='1'
mihomo.proxy.ipv6_proxy='0'
mihomo.proxy.router_proxy='1'
mihomo.proxy.lan_proxy='1'
mihomo.proxy.access_control_mode='allow'
mihomo.proxy.bypass_china_mainland_ip='1'
mihomo.proxy.acl_tcp_dport='21 22 80 110 143 194 443 465 993 995 8080 8443'
mihomo.proxy.acl_udp_dport='123 443 8443'
mihomo.proxy.acl_ip='192.168.11.9' '192.168.11.71' '192.168.11.12' '192.168.11.16'
mihomo.mixin=mixin
mihomo.mixin.log_level='info'
mihomo.mixin.mode='rule'
mihomo.mixin.match_process='off'
mihomo.mixin.ipv6='1'
mihomo.mixin.tcp_keep_alive_idle='600'
mihomo.mixin.tcp_keep_alive_interval='15'
mihomo.mixin.ui_name='metacubexd'
mihomo.mixin.ui_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
mihomo.mixin.api_port='9090'
mihomo.mixin.selection_cache='1'
mihomo.mixin.allow_lan='0'
mihomo.mixin.http_port='8080'
mihomo.mixin.socks_port='1080'
mihomo.mixin.mixed_port='7890'
mihomo.mixin.redir_port='7891'
mihomo.mixin.tproxy_port='7892'
mihomo.mixin.authentication='1'
mihomo.mixin.tun_stack='system'
mihomo.mixin.tun_mtu='9000'
mihomo.mixin.tun_gso='1'
mihomo.mixin.tun_gso_max_size='65536'
mihomo.mixin.tun_endpoint_independent_nat='0'
mihomo.mixin.dns_port='1053'
mihomo.mixin.dns_mode='redir-host'
mihomo.mixin.fake_ip_range='198.18.0.1/16'
mihomo.mixin.fake_ip_filter='0'
mihomo.mixin.fake_ip_filters='+.lan' '+.local'
mihomo.mixin.fake_ip_cache='1'
mihomo.mixin.dns_respect_rules='0'
mihomo.mixin.dns_doh_prefer_http3='0'
mihomo.mixin.dns_ipv6='0'
mihomo.mixin.dns_system_hosts='0'
mihomo.mixin.dns_hosts='1'
mihomo.mixin.hosts='0'
mihomo.mixin.dns_nameserver='0'
mihomo.mixin.dns_nameserver_policy='1'
mihomo.mixin.geoip_format='dat'
mihomo.mixin.geodata_loader='standard'
mihomo.mixin.geosite_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
mihomo.mixin.geoip_mmdb_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
mihomo.mixin.geoip_dat_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
mihomo.mixin.geoip_asn_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
mihomo.mixin.geox_auto_update='0'
mihomo.mixin.geox_update_interval='24'
mihomo.mixin.api_secret='905491'
mihomo.mixin.outbound_interface='wan'
mihomo.@authentication[0]=authentication
mihomo.@authentication[0].enabled='1'
mihomo.@authentication[0].username='mihomo'
mihomo.@authentication[0].password='905491'
mihomo.@host[0]=host
mihomo.@host[0].enabled='0'
mihomo.@host[0].domain_name='localhost'
mihomo.@host[0].ip='127.0.0.1' '::1'
mihomo.@nameserver[0]=nameserver
mihomo.@nameserver[0].enabled='1'
mihomo.@nameserver[0].type='default-nameserver'
mihomo.@nameserver[0].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[1]=nameserver
mihomo.@nameserver[1].enabled='1'
mihomo.@nameserver[1].type='proxy-server-nameserver'
mihomo.@nameserver[1].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[2]=nameserver
mihomo.@nameserver[2].enabled='1'
mihomo.@nameserver[2].type='direct-nameserver'
mihomo.@nameserver[2].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[3]=nameserver
mihomo.@nameserver[3].enabled='1'
mihomo.@nameserver[3].type='nameserver'
mihomo.@nameserver[3].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[4]=nameserver
mihomo.@nameserver[4].enabled='0'
mihomo.@nameserver[4].type='fallback'
mihomo.@nameserver[4].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.@nameserver_policy[0]=nameserver_policy
mihomo.@nameserver_policy[0].enabled='1'
mihomo.@nameserver_policy[0].matcher='geosite:cn,private'
mihomo.@nameserver_policy[0].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver_policy[1]=nameserver_policy
mihomo.@nameserver_policy[1].enabled='1'
mihomo.@nameserver_policy[1].matcher='geosite:geolocation-!cn'
mihomo.@nameserver_policy[1].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.editor=editor
mihomo.log=log
```

### 配置文件

```
# 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7890
# TCP 并发连接所有 IP, 将使用最快握手的 TCP
tcp-concurrent: true
# 允许局域网的连接（可用来共享代理）
allow-lan: false
# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录  
ipv6: true
# 规则模式：rule/global/direct/script
mode: rule
# 设置日志输出级别: silent/error/warning/info/debug
log-level: info
# 全局 TLS 指纹
global-client-fingerprint: chrome
# 匹配所有进程（always/strict/off）
find-process-mode: strict

# 使用geoip.dat数据库
geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
                         
profile:
  # 存储 select 选择记录
  store-selected: true
  # 持久化 fake-ip
  store-fake-ip: true

# 嗅探域名 可选配置
sniffer:               
  enable: true
  # 是否使用嗅探结果作为实际访问，默认 true
  parse-pure-ip: true  
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    QUIC:
      ports: [443, 8443]

# Tun 配置  
tun:
  enable: true
  # 可选： system/gvisor/mixed；
  stack: mixed
  # dns劫持,一般设置为 any:53 即可, 即劫持所有53端口的udp流量
  dns-hijack: [any:53]
  # 自动设置全局路由，可以自动将全局流量路由进入tun网卡。
  auto-route: true
  # 自动识别出口网卡
  auto-detect-interface: true
        
dns:
  enable: true
  # IPV6解析开关；如果为false，将返回ipv6结果为空
  ipv6: false
  # 模式：redir-host或fake-ip
  enhanced-mode: redir-host
  # DNS监听地址
  listen: 0.0.0.0:1053
  # Fake-IP解析地址池
  fake-ip-range: 198.18.0.1/16
  # fakeip 过滤，以下地址不会下发 fakeip 映射用于连接
  fake-ip-filter: ['*.lan','*.direct']
  # 默认的域名解析服务器
  # nameserver: [223.5.5.5, 119.29.29.29]                     
    
# 策略组引用相关参数
pg: &pg {type: select, proxies: [Proxy, 香港节点, 台湾节点, 日本节点, 美国节点, 狮城节点, DIRECT]}
# 订阅更新和延迟测试相关参数
p: &p {type: http, interval: 86400, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 1800}}
# 自动选择策略组：选取延迟最低节点
auto: &auto {type: url-test, lazy: true, url: "https://www.gstatic.com/generate_204", interval: 900, include-all-providers: true}
# 手动选择策略组：手动选择想要的节点/策略组
select: &select {type: select, include-all-providers: true}
# 故障回退策略组：策略组将按顺序选择你列表中第一个可用的节点
fallback: &fallback {type: fallback, lazy: true, url: "https://www.gstatic.com/generate_204", interval: 900, include-all-providers: true}
# 负载均衡策略组：不同的请求将使用不同的代理节点
load-balance: &load-balance {type: load-balance, lazy: true, url: "https://www.gstatic.com/generate_204", interval: 900, include-all-providers: true}
# classical规则相关
c: &c {type: http, behavior: classical, interval: 86400}
# domain规则相关
d: &d {type: http, behavior: domain, interval: 86400}
# ipcidr规则相关
i: &i {type: http, behavior: ipcidr, interval: 86400}

proxy-providers:
               
proxies:

proxy-groups:
  
rule-providers:

rules:


```

### 插件日志

```
[2024-10-18 13:04:55] App is enabled.
[2024-10-18 13:04:55] Starting...
[2024-10-18 13:04:56] Use Profile: mihomo.yaml
[2024-10-18 13:04:56] Mixin is enabled, mixin all config.
[2024-10-18 13:04:56] Profile testing...
[2024-10-18 13:04:58] Profile test passed!
[2024-10-18 13:04:58] Start Core
[2024-10-18 13:04:58] Transparent Proxy is enabled.
[2024-10-18 13:04:58] Transparent Proxy: Start.
[2024-10-18 13:04:58] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-10-18 13:04:58] Transparent Proxy: IPv6 DNS Hijack is enabled, IPv6 dns request will redirect to the core.
[2024-10-18 13:04:58] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-10-18 13:04:58] Transparent Proxy: IPv6 Proxy is enabled, set proxy for IPv6 traffic.
[2024-10-18 13:04:58] Transparent Proxy: Bypass china mainland ip is enabled.
[2024-10-18 13:04:59] Transparent Proxy: Destination TCP Port to Proxy: 21 22 80 110 143 194 443 465 993 995 8080 8443.
[2024-10-18 13:04:59] Transparent Proxy: Destination UDP Port to Proxy: 123 443 8443.
[2024-10-18 13:05:00] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-10-18 13:05:00] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-10-18 13:05:00] Transparent Proxy: Access Control is using allow mode, set proxy for client which is in acl.
[2024-10-18 13:05:01] Start Successful!

```

### 核心日志

在评论里提供
