### ISSUE TITLE
版本1.9.0-1核心alpha-3e966e8版无法启动，日志显示已启动且无报错

### ISSUE THREAD

**Issue by ali2liu** [morytyann/OpenWrt-mihomo#251]
### 自查

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [x] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

ImmortalWrt

### 系统版本

ImmortalWrt SNAPSHOT r32134-0b7d76327b

### 插件版本

1.9.0-1

### 核心版本

alpha-3e966e8

### 硬件架构

x86_64

### BUG 描述

不能启动

### 预期行为

正常启动

### 复现步骤

重载和重启服务

### 插件配置

config status 'status'

config config 'config'
	option init '1'
	option enabled '1'
	option scheduled_restart '0'
	option cron_expression '0 3 * * *'
	option profile 'file:configfull_v4.yaml'
	option mixin '1'
	option test_profile '1'
	option fast_reload '1'

config proxy 'proxy'
	option transparent_proxy '1'
	option tcp_transparent_proxy_mode 'tproxy'
	option udp_transparent_proxy_mode 'tproxy'
	option ipv4_dns_hijack '1'
	option ipv6_dns_hijack '1'
	option ipv4_proxy '1'
	option ipv6_proxy '0'
	option router_proxy '1'
	option lan_proxy '1'
	option access_control_mode 'all'
	option bypass_china_mainland_ip '0'
	option acl_tcp_dport '0-65535'
	option acl_udp_dport '0-65535'

config subscription 'subscription'
	option name 'default'
	option url 'http://example.com/default.yaml'
	option user_agent 'clash'

config mixin 'mixin'
	option log_level 'info'
	option mode 'rule'
	option match_process 'off'
	option ipv6 '0'
	option tcp_keep_alive_idle '600'
	option tcp_keep_alive_interval '15'
	option ui_name 'metacubexd'
	option ui_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
	option api_port '9090'
	option selection_cache '1'
	option allow_lan '1'
	option http_port '7890'
	option socks_port '7891'
	option mixed_port '7893'
	option redir_port '7892'
	option tproxy_port '7894'
	option authentication '1'
	option tun_stack 'system'
	option tun_mtu '9000'
	option tun_gso '1'
	option tun_gso_max_size '65536'
	option tun_endpoint_independent_nat '0'
	option dns_port '1053'
	option dns_mode 'fake-ip'
	option fake_ip_range '198.18.0.1/16'
	option fake_ip_filter '1'
	option fake_ip_cache '1'
	option dns_respect_rules '1'
	option dns_doh_prefer_http3 '0'
	option dns_ipv6 '0'
	option dns_system_hosts '0'
	option dns_hosts '0'
	option hosts '0'
	option dns_nameserver '1'
	option dns_nameserver_policy '1'
	option geoip_format 'dat'
	option geodata_loader 'memconservative'
	option geosite_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
	option geoip_mmdb_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
	option geoip_dat_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
	option geoip_asn_url 'https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
	option geox_auto_update '0'
	option geox_update_interval '24'
	option api_secret '635574'
	list fake_ip_filters '+.lan'
	list fake_ip_filters '+.local'
	list fake_ip_filters '+.gitlab.com'
	option fake_ip_filter_mode 'blacklist'

config authentication
	option enabled '1'
	option username 'mihomo'
	option password '635574'

config host
	option enabled '0'
	option domain_name 'localhost'
	list ip '127.0.0.1'
	list ip '::1'

config nameserver
	option enabled '1'
	option type 'default-nameserver'
	list nameserver '223.5.5.5'
	list nameserver '119.29.29.29'

config nameserver
	option enabled '1'
	option type 'proxy-server-nameserver'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'

config nameserver
	option enabled '1'
	option type 'nameserver'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'

config nameserver
	option enabled '0'
	option type 'fallback'
	list nameserver 'https://dns.cloudflare.com/dns-query'
	list nameserver 'https://dns.google/dns-query'

config nameserver_policy
	option enabled '1'
	option matcher 'geosite:cn,private'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'

config nameserver_policy
	option enabled '1'
	option matcher 'geosite:geolocation-!cn'
	list nameserver 'https://dns.cloudflare.com/dns-query'
	list nameserver 'https://dns.google/dns-query'

config editor 'editor'

config log 'log'

### 配置文件

```yaml
# 锚点
pr: &pr {type: select, proxies: [🚀 节点选择, 🔯 香港故转, 🔯 日本故转, ♻️ 香港自动, ♻️ 日本自动, ♻️ 美国自动, ♻️ 欧洲自动,♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 🌐 全部节点, ⭕ 欧洲节点, 🔗 链式代理, 🟢 直连]}

# 机场订阅，名称不能重复
proxy-providers:
  Airport_01:
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 🟢 直连
    url: ""
    override:
      skip-cert-verify: true
      udp: true      

  Airport_02:
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 🟢 直连
    url: ""
# 用于下载订阅时指定UA
global-ua: clash.meta

# 全局配置
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
# interface-name: eth0  （路由器下根据情况指定出站接口）
authentication:
  - name:passwd
  
geodata-mode: false
# GEO 文件加载模式（standard：标准加载器/memconservative：专为内存受限 (小内存) 设备优化的加载器 (默认值)）
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  
# 控制面板
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-url: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
# 下载面板地址可更换：https://mirror.ghproxy.com/https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip

# 匹配进程 always/strict/off
find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# 策略组选择和fakeip缓存
profile:
  store-selected: true
  store-fake-ip: true
  
# 流量嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
    
# 代理模式
tun:
  enable: true
  stack: mixed
  mtu: 9000
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  
# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: true
  # 模式切换 redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  # 模式切换 whitelist/blacklist 
  # 黑名单模式表示如果匹配成功则不返回 Fake-IP, 白名单模式时只有匹配成功才返回 Fake-IP
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - geosite:private
    - geosite:cn
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "rule-set:private_domain,cn_domain":
    - 223.5.5.5
    - 119.29.29.29
    "rule-set:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"
 
   
proxies:
- name: "🟢 直连"
  type: direct
  udp: true

  
# 策略组
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [🔯 香港故转, 🔯 日本故转, ♻️ 香港自动, ♻️ 日本自动, ♻️ 美国自动, ♻️ 欧洲自动,♻️ 自动选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 🌐 全部节点, ⭕ 欧洲节点, 🔗 链式代理, 🟢 直连]}
  - {name: 🛑 广告拦截, type: select, proxies: [REJECT,🟢 直连, 🚀 节点选择]}
  - {name: 📹 YouTube, <<: *pr}
  - {name: 🍀 Google, <<: *pr}
  - {name: 🤖 ChatGPT, <<: *pr}
  - {name: 👨🏿‍💻 GitHub, <<: *pr}
  - {name: 🐬 OneDrive, <<: *pr}
  - {name: 🪟 Microsoft, <<: *pr}
  - {name: 🎵 TikTok, <<: *pr}
  - {name: 📲 Telegram, <<: *pr}
  - {name: 🎥 NETFLIX, <<: *pr}
  - {name: ✈️ Speedtest, <<: *pr}
  - {name: 💶 PayPal, <<: *pr}
  - {name: 🍎 Apple, type: select, proxies: [🟢 直连, 🚀 节点选择]}
  - {name: 🔗 链式代理, type: relay, proxies: [🇺🇲 美国节点, ⭕ 欧洲节点]}
  - {name: 🎯 全球直连, type: select, proxies: [🟢 直连, 🚀 节点选择]}
  - {name: 🐟 漏网之鱼, <<: *pr}
  - {name: ⭕ 欧洲节点, type: select, include-all: true, filter: "(?i)欧|EU|eu|PL|de"}
  - {name: 🇭🇰 香港节点, type: select, include-all: true, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: 🇯🇵 日本节点, type: select, include-all: true, filter: "(?i)日|jp|japan"}
  - {name: 🇺🇲 美国节点, type: select, include-all: true, filter: "(?i)美|us|unitedstates|united states"}
  - {name: 🔯 香港故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$"}
  - {name: 🔯 日本故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$" }
  - {name: ♻️ 香港自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|欧|美)).)*$"}
  - {name: ♻️ 日本自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美|欧)).)*$" }
  - {name: ♻️ 美国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|日|韩|新|欧)).)*$"}
  - {name: ♻️ 欧洲自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(欧|EU|eu|PL|de(?i)Europe))^((?!(港|台|日|韩|新|美)).)*$"}
  - {name: ♻️ 自动选择, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(直连)).)*$"}
  - {name: 🌐 全部节点, type: select, include-all: true}
rules:
  - RULE-SET,adblock,🛑 广告拦截
  - RULE-SET,private_domain,🟢 直连
  - RULE-SET,direct1,🟢 直连
  - RULE-SET,apple_domain,🍎 Apple
  - RULE-SET,free,🔗 链式代理
  - RULE-SET,proxylite,🚀 节点选择
  - RULE-SET,ai,🤖 ChatGPT
  - RULE-SET,github_domain,👨🏿‍💻 GitHub
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,google_domain,🍀 Google
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🪟 Microsoft
  - RULE-SET,tiktok_domain,🎵 TikTok
  - RULE-SET,speedtest_domain,✈️ Speedtest
  - RULE-SET,telegram_domain,📲 Telegram
  - RULE-SET,netflix_domain,🎥 NETFLIX
  - RULE-SET,paypal_domain,💶 PayPal
  - RULE-SET,geolocation-!cn,🚀 节点选择
  - RULE-SET,cn_domain,🎯 全球直连
  - RULE-SET,google_ip,🍀 Google,no-resolve
  - RULE-SET,netflix_ip,🎥 NETFLIX,no-resolve
  - RULE-SET,telegram_ip,📲 Telegram,no-resolve
  - RULE-SET,cn_ip,🎯 全球直连
  - MATCH,🚀 节点选择
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qcy: &qcy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }
  direct1: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/master/Direct.list" }
  proxylite: { <<: *qcy, url: "https://raw.githubusercontent.com/qichiyuhub/rule/master/ProxyLite.list" }
  adblock: { <<: *domain, url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/adblockplus.mrs" }
  ai: { <<: *qcy, url: "https://raw.githubusercontent.com/qichiyuhub/rule/master/AI.list" }
  free: { <<: *qcy, url: "https://raw.githubusercontent.com/qichiyuhub/rule/master/Free.list" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs" }
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs" }
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs" }
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs" }
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs" }
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs" }
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }
  
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs" }
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }
```

### 插件日志

[2024-10-22 10:56:06] App is enabled.
[2024-10-22 10:56:06] Starting...
[2024-10-22 10:56:06] Use Profile: configfull_v4.yaml
[2024-10-22 10:56:06] Mixin is enabled, mixin all config.
[2024-10-22 10:56:06] Profile testing...
[2024-10-22 10:56:08] Profile test passed!
[2024-10-22 10:56:08] Start Core
[2024-10-22 10:56:08] Transparent Proxy is enabled.
[2024-10-22 10:56:08] Transparent Proxy: Start.
[2024-10-22 10:56:08] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-10-22 10:56:08] Transparent Proxy: IPv6 DNS Hijack is enabled, IPv6 dns request will redirect to the core.
[2024-10-22 10:56:08] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-10-22 10:56:08] Transparent Proxy: IPv6 Proxy is enabled, set proxy for IPv6 traffic.
[2024-10-22 10:56:08] Transparent Proxy: Destination TCP Port to Proxy: 0-65535.
[2024-10-22 10:56:08] Transparent Proxy: Destination UDP Port to Proxy: 0-65535.
[2024-10-22 10:56:08] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-10-22 10:56:08] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-10-22 10:56:08] Transparent Proxy: Access Control is using all mode, set proxy for all client.
[2024-10-22 10:56:08] Start Successful!

### 核心日志

time="2024-10-22T10:56:06.824475114+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-22T10:56:06.826614307+08:00" level=warning msg="The group [🔗 链式代理] with relay type is deprecated, please using dialer-proxy instead"
time="2024-10-22T10:56:06.829203016+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-22T10:56:06.829255618+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-22T10:56:06.830049864+08:00" level=info msg="Load GeoSite rule: cn"
time="2024-10-22T10:56:07.870052575+08:00" level=info msg="Finished initial GeoSite rule cn => dns.nameserver-policy, records: 92268"
time="2024-10-22T10:56:07.870307247+08:00" level=info msg="Load GeoSite rule: private"
time="2024-10-22T10:56:07.917941275+08:00" level=info msg="Finished initial GeoSite rule private => dns.nameserver-policy, records: 131"
time="2024-10-22T10:56:07.91816828+08:00" level=info msg="Load GeoSite rule: geolocation-!cn"
time="2024-10-22T10:56:08.243010824+08:00" level=info msg="Finished initial GeoSite rule geolocation-!cn => dns.nameserver-policy, records: 30934"
time="2024-10-22T10:56:08.243291011+08:00" level=info msg="Finished initial GeoSite rule private => dns.fake-ip-filter, records: 131"
time="2024-10-22T10:56:08.243388606+08:00" level=info msg="Finished initial GeoSite rule cn => dns.fake-ip-filter, records: 92268"
time="2024-10-22T10:56:08.244247263+08:00" level=info msg="Initial configuration complete, total time: 1419ms"
configuration file /etc/mihomo/run/config.yaml test is successful
