### ISSUE TITLE
[BUG]启动后面板无连接，无法代理

### ISSUE THREAD

**Issue by FNTDemo** [morytyann/OpenWrt-mihomo#252]
### 自查

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

ImmortalWrt

### 系统版本

23.05

### 插件版本

1.9.0

### 核心版本

alpha-3e966e8

### 硬件架构

aarch64_cortex-a53

### BUG 描述

启动后面板无连接，无法代理

### 预期行为

不清楚

### 复现步骤

添加订阅，启动

### 插件配置

mihomo.status=status
mihomo.config=config
mihomo.config.enabled='1'
mihomo.config.scheduled_restart='0'
mihomo.config.cron_expression='0 3 * * *'
mihomo.config.profile='subscription:subscription'
mihomo.config.mixin='1'
mihomo.config.test_profile='1'
mihomo.config.fast_reload='1'
mihomo.proxy=proxy
mihomo.proxy.transparent_proxy='1'
mihomo.proxy.tcp_transparent_proxy_mode='tproxy'
mihomo.proxy.udp_transparent_proxy_mode='tproxy'
mihomo.proxy.ipv4_dns_hijack='1'
mihomo.proxy.ipv6_dns_hijack='1'
mihomo.proxy.ipv4_proxy='1'
mihomo.proxy.ipv6_proxy='0'
mihomo.proxy.router_proxy='1'
mihomo.proxy.lan_proxy='1'
mihomo.proxy.access_control_mode='all'
mihomo.proxy.bypass_china_mainland_ip='0'
mihomo.proxy.acl_tcp_dport='21 22 80 110 143 194 443 465 993 995 8080 8443'
mihomo.proxy.acl_udp_dport='123 443 8443'
mihomo.subscription=subscription
mihomo.subscription.name='Mitce'
mihomo.subscription.url='https://app.mitce.com/?sid=167690&token=srvkxdjn'
mihomo.subscription.user_agent='clash'
mihomo.mixin=mixin
mihomo.mixin.log_level='warning'
mihomo.mixin.mode='rule'
mihomo.mixin.match_process='off'
mihomo.mixin.ipv6='0'
mihomo.mixin.tcp_keep_alive_idle='600'
mihomo.mixin.tcp_keep_alive_interval='15'
mihomo.mixin.ui_name='metacubexd'
mihomo.mixin.ui_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
mihomo.mixin.api_port='9090'
mihomo.mixin.selection_cache='1'
mihomo.mixin.allow_lan='1'
mihomo.mixin.http_port='8080'
mihomo.mixin.socks_port='1080'
mihomo.mixin.mixed_port='7890'
mihomo.mixin.redir_port='7891'
mihomo.mixin.tproxy_port='7892'
mihomo.mixin.authentication='1'
mihomo.mixin.tun_stack='mixed'
mihomo.mixin.tun_mtu='9000'
mihomo.mixin.tun_gso='1'
mihomo.mixin.tun_gso_max_size='65536'
mihomo.mixin.tun_endpoint_independent_nat='0'
mihomo.mixin.dns_port='1053'
mihomo.mixin.dns_mode='fake-ip'
mihomo.mixin.fake_ip_range='198.18.0.1/16'
mihomo.mixin.fake_ip_filter='0'
mihomo.mixin.fake_ip_filters='+.lan' '+.local'
mihomo.mixin.fake_ip_cache='1'
mihomo.mixin.dns_respect_rules='0'
mihomo.mixin.dns_doh_prefer_http3='0'
mihomo.mixin.dns_ipv6='0'
mihomo.mixin.dns_system_hosts='0'
mihomo.mixin.dns_hosts='1'
mihomo.mixin.hosts='0'
mihomo.mixin.dns_nameserver='0'
mihomo.mixin.dns_nameserver_policy='0'
mihomo.mixin.geoip_format='dat'
mihomo.mixin.geodata_loader='memconservative'
mihomo.mixin.geosite_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
mihomo.mixin.geoip_mmdb_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
mihomo.mixin.geoip_dat_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
mihomo.mixin.geoip_asn_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
mihomo.mixin.geox_auto_update='0'
mihomo.mixin.geox_update_interval='24'
mihomo.mixin.api_secret='594717'
mihomo.@authentication[0]=authentication
mihomo.@authentication[0].enabled='1'
mihomo.@authentication[0].username='mihomo'
mihomo.@authentication[0].password='594717'
mihomo.@host[0]=host
mihomo.@host[0].enabled='0'
mihomo.@host[0].domain_name='localhost'
mihomo.@host[0].ip='127.0.0.1' '::1'
mihomo.@nameserver[0]=nameserver
mihomo.@nameserver[0].enabled='1'
mihomo.@nameserver[0].type='default-nameserver'
mihomo.@nameserver[0].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[1]=nameserver
mihomo.@nameserver[1].enabled='1'
mihomo.@nameserver[1].type='proxy-server-nameserver'
mihomo.@nameserver[1].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[2]=nameserver
mihomo.@nameserver[2].enabled='1'
mihomo.@nameserver[2].type='direct-nameserver'
mihomo.@nameserver[2].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[3]=nameserver
mihomo.@nameserver[3].enabled='1'
mihomo.@nameserver[3].type='nameserver'
mihomo.@nameserver[3].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[4]=nameserver
mihomo.@nameserver[4].enabled='0'
mihomo.@nameserver[4].type='fallback'
mihomo.@nameserver[4].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.@nameserver_policy[0]=nameserver_policy
mihomo.@nameserver_policy[0].enabled='1'
mihomo.@nameserver_policy[0].matcher='geosite:cn,private'
mihomo.@nameserver_policy[0].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver_policy[1]=nameserver_policy
mihomo.@nameserver_policy[1].enabled='1'
mihomo.@nameserver_policy[1].matcher='geosite:geolocation-!cn'
mihomo.@nameserver_policy[1].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.editor=editor
mihomo.log=log

### 配置文件

```yaml
port: 8080
socks-port: 1080
allow-lan: true
mode: rule
log-level: warning
external-controller: '0.0.0.0:9090'
proxies:
  -
rule-providers:
  reject: {type: http, behavior: domain, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/reject.txt', path: ./ruleset/reject.yaml, interval: 86400}
  icloud: {type: http, behavior: domain, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/icloud.txt', path: ./ruleset/icloud.yaml, interval: 86400}
  apple: {type: http, behavior: domain, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/apple.txt', path: ./ruleset/apple.yaml, interval: 86400}
  google: {type: http, behavior: domain, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/google.txt', path: ./ruleset/google.yaml, interval: 86400}
  proxy: {type: http, behavior: domain, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/proxy.txt', path: ./ruleset/proxy.yaml, interval: 86400}
  direct: {type: http, behavior: domain, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/direct.txt', path: ./ruleset/direct.yaml, interval: 86400}
  cncidr: {type: http, behavior: ipcidr, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/cncidr.txt', path: ./ruleset/cncidr.yaml, interval: 86400}
  lancidr: {type: http, behavior: ipcidr, url: 'https://raw.v2raysocks.com/Loyalsoldier/clash-rules/release/lancidr.txt', path: ./ruleset/lancidr.yaml, interval: 86400}
rules:
  - 'PROCESS-NAME,v2ray,DIRECT'
  - 'PROCESS-NAME,Surge%203,DIRECT'
  - 'PROCESS-NAME,ss-local,DIRECT'
  - 'PROCESS-NAME,privoxy,DIRECT'
  - 'PROCESS-NAME,trojan,DIRECT'
  - 'PROCESS-NAME,trojan-go,DIRECT'
  - 'PROCESS-NAME,naive,DIRECT'
  - 'PROCESS-NAME,Thunder,DIRECT'
  - 'PROCESS-NAME,DownloadService,DIRECT'
  - 'PROCESS-NAME,qBittorrent,DIRECT'
  - 'PROCESS-NAME,Transmission,DIRECT'
  - 'PROCESS-NAME,fdm,DIRECT'
  - 'PROCESS-NAME,aria2c,DIRECT'
  - 'PROCESS-NAME,Folx,DIRECT'
  - 'PROCESS-NAME,NetTransport,DIRECT'
  - 'PROCESS-NAME,uTorrent,DIRECT'
  - 'PROCESS-NAME,WebTorrent,DIRECT'
  - 'RULE-SET,icloud,Apple Services'
  - 'RULE-SET,apple,Apple Services'
  - 'RULE-SET,google,Google Services'
  - 'RULE-SET,proxy,Blocked Domains'
  - 'RULE-SET,cncidr,CHN Mainland'
  - 'RULE-SET,direct,DIRECT'
  - 'RULE-SET,lancidr,DIRECT,no-resolve'
  - 'MATCH,Main Node'
find-process-mode: off
keep-alive-idle: 600
keep-alive-interval: 15
ipv6: false
external-ui: ui
external-ui-name: metacubexd
external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
secret: 594717
profile:
  store-selected: true
  store-fake-ip: true
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
tun:
  enable: false
  stack: mixed
  device: mihomo
  mtu: 9000
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: false
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  respect-rules: false
  prefer-h3: false
  ipv6: false
  use-system-hosts: false
  use-hosts: true
geodata-mode: true
geodata-loader: memconservative
geox-url:
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  asn: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
geo-auto-update: false
geo-update-interval: 24
authentication:
  - mihomo:594717
```

### 插件日志

[2024-10-23 00:43:24] App is enabled.
[2024-10-23 00:43:24] Starting...
[2024-10-23 00:43:26] Use Subscription: Mitce
[2024-10-23 00:43:26] Mixin is enabled, mixin all config.
[2024-10-23 00:43:26] Profile testing...
[2024-10-23 00:43:26] Profile test passed!
[2024-10-23 00:43:26] Start Core
[2024-10-23 00:43:26] Transparent Proxy is enabled.
[2024-10-23 00:43:26] Transparent Proxy: Start.
[2024-10-23 00:43:27] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-10-23 00:43:27] Transparent Proxy: IPv6 DNS Hijack is enabled, IPv6 dns request will redirect to the core.
[2024-10-23 00:43:27] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-10-23 00:43:27] Transparent Proxy: Destination TCP Port to Proxy: 21 22 80 110 143 194 443 465 993 995 8080 8443.
[2024-10-23 00:43:27] Transparent Proxy: Destination UDP Port to Proxy: 123 443 8443.
[2024-10-23 00:43:29] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-10-23 00:43:29] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-10-23 00:43:29] Transparent Proxy: Access Control is using all mode, set proxy for all client.
[2024-10-23 00:43:29] Start Successful!

### 核心日志

time="2024-10-23T00:43:26.581127578+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-23T00:43:26.643160525+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.643382532+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.643541856+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.64370249+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.643860351+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.644464998+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.644626325+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.64478434+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.6449479+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.645114617+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.645283259+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.645458138+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.645613536+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.645776017+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:26.649517484+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-23T00:43:26.649617437+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-23T00:43:26.651392876+08:00" level=info msg="Initial configuration complete, total time: 70ms"
configuration file /etc/mihomo/run/config.yaml test is successful
time="2024-10-23T00:43:29.939054537+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-23T00:43:29.985550619+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.985775475+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.985936648+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.986088272+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.986242437+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.986935255+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.987093424+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.987268766+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.987435714+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.987594114+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.987774384+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.987937636+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.988115904+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.988270223+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2024-10-23T00:43:29.991907655+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-23T00:43:29.992010842+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-23T00:43:29.992854977+08:00" level=info msg="Initial configuration complete, total time: 53ms"
