### ISSUE TITLE
通过wireguard（VPN）连接到路由器无法进行透明代理，只能使用socks手动连接

### ISSUE THREAD

**Issue by zhoufla** [morytyann/OpenWrt-mihomo#32]
路由lan网段：192.168.10.1/24
wireguard网段：192.168.30.1/24
wireguard允许路由的ip：0.0.0.0/0
查看核心日志未找到30段的访问记录。
如果手动指定socks代理，则可以正常代理。
![image](https://github.com/user-attachments/assets/c1e3f19b-aa7d-4e94-a450-64ec20971d90)

**Comment by morytyann** [comment]
我测了两次，都是在没有连接WiFi的设备上连接的WireGuard，第一次开启了白名单模式，不能透明代理，第二次关闭了访问控制，可以透明代理，你有没有开访问控制？

**Comment by zhoufla** [comment]
> 我测了两次，都是在没有连接WiFi的设备上连接的WireGuard，第一次开启了白名单模式，不能透明代理，第二次关闭了访问控制，可以透明代理，你有没有开访问控制？

有的，我开启了黑名单模式。

**Comment by zhoufla** [comment]
> > 我测了两次，都是在没有连接WiFi的设备上连接的WireGuard，第一次开启了白名单模式，不能透明代理，第二次关闭了访问控制，可以透明代理，你有没有开访问控制？
> 
> 有的，我开启了黑名单模式。

有一台nas和一台亚瑟被我设为了黑名单，不走核心。

**Comment by morytyann** [comment]
WireGuard的DNS配置了吗？配置上，再关掉访问控制试试。

**Comment by zhoufla** [comment]
> WireGuard的DNS配置了吗？配置上，再关掉访问控制试试。

不开访问控制时，通过wireguard连接的设备可以透明代理，开了就不行。

**Comment by morytyann** [comment]
> 不开访问控制时，通过wireguard连接的设备可以透明代理，开了就不行。

贴一下透明代理那一节的配置吧，注意脱敏

**Comment by zhoufla** [comment]
没做啥特殊的配置，只在配置文件中定义了节点信息和路由规则。

```YAML
proxies:
  - 节点定义
proxy-providers:
  provider1:
    type: http
    url: "ur1"
    interval: 3600
    proxy: DIRECT
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
  provider2:
    type: http
    url: "url2"
    interval: 3600
    proxy: DIRECT
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: "PROXY"
    type: select
    disable-udp: true
    proxies:
      - "gcp-hk负载均衡"
      - "jp负载均衡"
      - "la256负载均衡"
      - "la负载均衡"
      - "hk699负载均衡"
      - "hk299负载均衡"

  - name: "gcp-hk负载均衡"
    type: load-balance
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin
    proxies:
      - gcp-hk-reality
      - gcp-hk-hy
  - name: "jp负载均衡"
    type: load-balance
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin
    proxies:
      - bv-jp-reality
      - bv-jp-hy-1
      - bv-jp-hy-2
      - bv-jp-hy-3
      - bv-jp-hy-4
      - bv-jp-hy-5
  - name: "la负载均衡"
    type: load-balance
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin
    proxies:
      - bv-la-1
      - bv-la-2
      - bv-la-3
      - bv-la-4
      - bv-la-5
      - bv-la-6
      - bv-la-7
      - bv-la-8
      - bv-la-9
  - name: "la256负载均衡"
    type: load-balance
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin
    proxies:
      - la256-ssr
      - la256-hy1
      - la256-hy2
      - la256-hy3
      - la256-hy4
      - la256-hy5
      - la256-hy6
  - name: "hk699负载均衡"
    type: load-balance
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin
    use:
      - provider1
  - name: "hk299负载均衡"
    type: load-balance
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    strategy: round-robin
    use:
      - provider2
rule-providers:
  cn:
    behavior: domain
    interval: 86400
    path: ./provider/rule-set/cn_domain.yaml
    type: http
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
    proxy: PROXY
rules:
  - RULE-SET,cn,DIRECT
  - DOMAIN-SUFFIX,metacubex.one,PROXY
  - DOMAIN-SUFFIX,coze.com,PROXY
  - DOMAIN-SUFFIX,koyeb.com,PROXY
  - DOMAIN-SUFFIX,zerotier.com,PROXY
  - DOMAIN-SUFFIX,graalvm.org,PROXY
  - DOMAIN-SUFFIX,anyfastcloud.com,PROXY
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,private,DIRECT
  - GEOSITE,youtube,la256负载均衡
  - GEOSITE,openai,jp负载均衡
  - GEOSITE,google,PROXY
  - GEOSITE,twitter,PROXY
  - GEOSITE,pixiv,PROXY
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,biliintl,PROXY
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
  #GEOIP规则
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,PROXY
  - GEOIP,JP,PROXY
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
mode: rule
find-process-mode: off
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 600
log-level: info
external-ui: ui
external-controller: 0.0.0.0:9090
profile:
  store-selected: true
  store-fake-ip: true
allow-lan: true
port: 10080
socks-port: 10081
mixed-port: 10081
redir-port: 7891
tproxy-port: 7892
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-system-hosts: false
  use-hosts: false
sniffer:
  enable: false
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true

```
