### ISSUE TITLE
[BUG]订阅更新成功但找不到配置文件

### ISSUE THREAD

**Issue by refined-fish** [morytyann/OpenWrt-mihomo#324]
### 自查

- [X] OpenWrt 版本在 23.05 及以上
- [X] Linux Kernel 版本在 5.10 及以上
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经关闭了DNSMASQ的`DNS 重定向`选项（如无此项请忽略）
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到相关问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由此仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

ImmortalWrt

### BUG 描述

写入订阅连接后启动插件自动更新或者手动点击更新，日志提示更新成功，但又找不到文件，ssh查看确实没有在mihomo目录生成配置文件

### 预期行为

获取远程配置并启动

### 复现步骤

不方便公开订阅连接，如有需要可以以其他方式发送给作者

### 调试信息

应该与订阅连接的性质和openwrt-mihomo的获取订阅方式有关

### 插件日志

[2024-12-03 21:12:07] App is enabled.
[2024-12-03 21:12:07] Starting...
[2024-12-03 21:12:07] Use Subscription: 01_FISH.yaml.
[2024-12-03 21:12:07] Update Subscription: 01_FISH.yaml.
[2024-12-03 21:12:09] Subscription update succeed.
[2024-12-03 21:12:09] Subscription file not found.
[2024-12-03 21:12:09] Exiting...
[2024-12-03 21:22:16] Update Subscription: 01_FISH.yaml.
[2024-12-03 21:22:20] Subscription update succeed.

### 核心日志

核心未启动

### 附加信息

应该与订阅连接的性质和openwrt-mihomo的获取订阅方式有关，此订阅链接的资源是订阅文件内容本身，而不是订阅文件。
我设置了NGINX响应头`add_header Content-Disposition 'attachment; filename="XXX"';`来实现接受http请求时告知客户端下载，文件名为XXX，实测在mihomo的桌面客户端中此订阅连接工作正常，但是openwrt插件中并不正常

**Comment by refined-fish** [comment]
> 贴一下你nginx相关的配置，以及脱敏后的文件内容。

NGINX配置：
```
server {
  listen ;
  listen [::]:;
  
  resolver 127.0.0.1 valid=86400s;
  resolver_timeout 10s;
  
  set $github_proxy "https://ghp.ci/";
  set $subscription "https://raw.githubusercontent.com/XXX.yaml";
  set $subscription_URL "${github_proxy}${subscription}";
  set $github_token "github_pat_";
  
  location /01-FISH.yaml {
    proxy_ssl_server_name on;
    proxy_pass "${subscription_URL}";
    add_header Content-Disposition 'attachment; filename="XXX.yaml"';
    proxy_set_header Authorization "token ${github_token}";
    proxy_hide_header Authorization;
  }
}
```

订阅文件内容
```
###########################################################################################################################
mixed-port: 7890    #❗混合端口，HTTP和SOCKS5均可用的端口，系统代理走这个端口
socks-port: 1080      #❗SOCKS5 代理端口
port: 8080                #❗HTTP 代理端口
#redir-port: 7891     #❗Linux 和 macOS 的 redir 透明代理端口，其他客户端给了会报错
#tproxy-port: 7892  #❗Linux 和 macOS 的 tproxy 透明代理端口，其他客户端给了会报错

###########################################################################################################################
allow-lan: true             #❗允许局域网
bind-address: "*"         #❗绑定地址，仅允许通过此指定地址访问代理
lan-allowed-ips:          # 允许连接的客户端IP，默认允许全部
  - 0.0.0.0/0
  - ::/0
lan-disallowed-ips:            # 禁止连接的IP，优先级高于允许的白名单，默认为空
  - ~
authentication:                  # http(s)/socks/mixed 代理的用户验证，格式："user1:pass1"
  - ~
skip-auth-prefixes:            # 允许跳过用户验证的IP
  - ~
mode: rule                          # 运行模式：规则模式：rule（规则） / global（全局代理）/ direct（全局直连）
log-level: warning              #❗日志级别 silent / error / warning / info / debug
ipv6: true                             #❗ipv6代理，内核是否接受ipv6流量
keep-alive-idle: 15             # 当链接无数据活动到达时间后 Clash 发出心跳包检测
keep-alive-interval: 15       # 如果心跳包未响应，则会等待时间后继续发送，重复最多9次
disable-keep-alive: false     # 禁用 keep alive，即允许链接一直存在。安卓端默认禁用
find-process-mode: strict   # 进程匹配模式，strict由clash决定是否开启，off为关闭，always为开启
external-controller: 0.0.0.0:9090   #❗API面板监听地址
secret: ""                               # API面板访问密钥
#external-ui: ui                      #❗静态资源的路径
#external-ui-name: metacubexd    #❗外部面板的名字，配合路径合并成特定面板的路径，例如/ui/metacubexd
#external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip   #❗外部面板下载地址
profile:                  # 缓存
  store-selected: true    # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true     # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址
unified-delay: false      # 统一延迟，意义在于让延迟变得好看，没啥卵用
tcp-concurrent: true      # TCP并发
#interface-name: en0      #❗clash流量出站接口，即接口绑定
#routing-mark: 6666       # Linux下的路由标记，为流量提供标记
global-client-fingerprint: random   # 全局客户端指纹，优先低于 proxy 内的 client-fingerprint，目前支持开启 TLS 传输的 TCP/grpc/WS/HTTP , 支持协议有 VLESS,Vmess 和 trojan
geodata-mode: true        # GEOIP数据模式，默认false是mmdb，true是dat，mmdb是更新的版本（实测有设备会不支持mmdb，例如IPQ6000）
geodata-loader: standard  # GEO文件加载模式，默认为memconservative（小内存设备模式）
geo-auto-update: true     # GEO自动更新
geo-update-interval: 24   # 更新间隔，小时
geox-url:                 # Geo数据库下载地址，会按需下载
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
global-ua: clash.meta     # 自定义全局UA，默认为clash.meta
etag-support: true        # 外部资源下载的 ETag 支持，默认为 true，Etag可用于对比请求资源与本地资源的区别，如果一致则发送304状态码，减轻服务端压力

###########################################################################################################################
dns:
  enable: true                    #❗是否启用dns
  prefer-h3: true                 # 优先使用HTTP/3，对于支持的DoH DNS能够加速访问
  listen: 0.0.0.0:1053            #❗DNS监听端口，仅支持udp
  ipv6: true                      # 是否解析ipv6地址，否则返回空结果
  enhanced-mode: redir-host       #❗DNS处理模式：redir-host/fake-ip，fake-ip速度更快但可能引入问题（部分网页会打不开，爱快缓存fakeip后无法故障切换）
  fake-ip-range: 198.18.0.1/16    # fakeip 下的 IP 段设置，tun接口的默认 IPV4 地址 也使用此值作为参考
  fake-ip-filter:                 # fakeip过滤，具体行为由黑/白名单决定
    - geosite:category-ads-all,category-games,cn,private
  fake-ip-filter-mode: blacklist  # 黑/白名单模式，白名单下 filter 会返回 fake-ip
  use-hosts: true                 # 查询配置文件中的hosts
  use-system-hosts: true          # 查询系统 hosts
  respect-rules: false            # DNS请求遵循路由规则，需先配置好 proxy-server-nameserver，否则解析节点IP时匹配到代理规则又没有解析节点IP无法连接节点时会冲突
  
  proxy-server-nameserver:        # 解析节点域名的服务器，不指定则解析请求会遵循namepolicy，一般节点域名都属于geo@cn，默认会使用cn的DNS服务器，有污染和识别风险
    - https://8.8.8.8/dns-query   # 谷歌主DNS
    - https://1.1.1.1/dns-query   # Cloudflare主DNS
    - https://1.0.0.1/dns-query   # Cloudflare次DNS
  
  nameserver-policy:              # 指定域名查询的解析服务器策略，优先级高于nameserver组
    geosite:cn,apple,private:     # 匹配中国，苹果域名，私有地址，优先使用运营商DNS
      - dhcp://wan                # 指定网卡获取的DNS，硬路由的wan口网卡名为wan
      - dhcp://eth1               # 指定网卡获取的DNS，软路由的wan口网卡名为最后一张网卡，双口就是eth1
      - 223.5.5.5                 # 阿里主DNS
      - 223.6.6.6                 # 阿里副DNS
    geosite:geolocation-!cn:      # 匹配非中国域名，应确保可信无污染且国外加密
      - https://8.8.8.8/dns-query
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query
    geosite:category-ads-all:     # 匹配广告域名，直接返回空结果
      - rcode://success           # 直接返回一个success也就是空结果
  
  nameserver:                     # 默认DNS组，域名未命中 nameserver-policy，就会用 nameserver/fallback 同时解析，并根据 fallback-filter 选择结果
    - dhcp://wan
    - dhcp://eth1
    - 223.5.5.5
    - 223.6.6.6

###########################################################################################################################
hosts:
  'mihomo.mihomo': 127.0.0.1

###########################################################################################################################
sniffer:                      # 嗅探的作用是获取握手包中的域名字段，让IP流量也可以匹配域名规则
  enable: true                # 启用sniffer
  force-dns-mapping: true     # 对redir-host类型识别的流量进行强制嗅探
  parse-pure-ip: true         # 对所有未获取到域名的流量进行强制嗅探
  override-destination: true  # 是否使用嗅探结果作为实际访问，默认为 true
  sniff:                      # 需要嗅探的协议类型，仅支持 HTTP/TLS/QUIC
    TLS:                      # TLS协议，不配置默认嗅探443端口
    HTTP:                     # HTTP协议
      ports:                  # 端口白名单，只针对下列端口嗅探，不配置则全部嗅探
        - 80
  force-domain:               # 强制嗅探的域名
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:                # 需要跳过嗅探的域名。主要解决部分站点sni字段非域名，导致嗅探结果异常的问题，如米家设备
    - "+.apple.com"
    - Mijia Cloud
    - dlg.io.mi.com
    - "+.oray.com"
    - "+.sunlogin.net"
    - geosite:cn

###########################################################################################################################
tun:
  enable: false                 #❗是否启用接口，一般情况下不使用tun模式
  stack: mixed                  # tun 堆栈模式，如无使用问题，建议使用 mixed：TCP使用system，UDP使用Gvisor
  device: utun0                 # 指定TUN网卡名称，MacOS 设备只能使用 utun 开头的网卡名
  auto-route: true              # 自动设置全局路由，可以自动将全局流量路由进入 tun 网卡
  auto-redirect: true           # 仅Linux有效，自动配置 iptables/nftables 以重定向 TCP 连接，需要auto-route: true
  auto-detect-interface: true   # 自动选择流量的出接口（wan）
  dns-hijack:                   # dns 劫持，将匹配到的连接导入内部 dns 模块，不指定UDP或tcp则默认为 udp://
    - any:53
    - tcp://any:53
  strict-route: true            # 严格路由，添加防火墙规则禁止Windows使用多DNS，有效防止DNS泄露
  mtu: 9000
  gso: true                     # 通用分段卸载
  gso-max-size: 65536           # 数据块最大长度
  endpoint-independent-nat: false # 独立于端点的 NAT，性能可能会略有下降，所以不建议在不需要的时候开启
  exclude-package:              # 安卓排除的包名
    - com.tencent.mobileqq      # QQ
    - com.tencent.mm            # 微信
    - com.tencent.androidqqmail # QQ邮箱
    - com.xingin.xhs            # 小红书
    - idm.internet.download.manager  # 1DM下载器
    - com.sausage.download      # 浩克下载
    - com.eg.android.AlipayGphone  # 支付宝
    - com.sgcc.wsgw.cn          # 网上国网
    - com.taobao.taobao         # 淘宝
    - com.jingdong.app.mall     # 京东
    - com.MobileTicket          # 铁路12306
    - com.chinamworld.main      # 中国建设银行
    - com.jd.jrapp              # 京东金融

###########################################################################################################################
proxy-providers:
  main:               # 代理集合名，不建议和策略组名字重复，里面不要包含符号和数字
    type: http        # 类型，可选http/file
    url: "https://sub.xeton.dev/sub?target=clash&config=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FSleepyHeeead%2Fsubconverter-config%40master%2Fremote-config%2Fspecial%2Fbasic.ini&url="
    interval: 86400   # 更新循环时间，单位秒
    proxy: DIRECT     # 指定代理组
    size-limit: 0     # 限制下载文件大小
    override:         # 覆写节点设置
      additional-prefix: "|"   # 添加固定前缀
      tfo: true               # 启用TCP Fast Open
      mptcp: false            # 启用TCP Multi Path
      udp: true               # 启用udp
      udp-over-tcp: false     # 启用 UDP over TCP
      skip-cert-verify: false # 跳过证书验证
  
  backup:
    type: http
    url: "https://sub.xeton.dev/sub?target=clash&config=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FSleepyHeeead%2Fsubconverter-config%40master%2Fremote-config%2Fspecial%2Fbasic.ini&url="
    interval: 86400
    proxy: DIRECT
    size-limit: 0
    override:
      additional-prefix: "|"
      tfo: true               # 启用TCP Fast Open
      mptcp: false            # 启用TCP Multi Path
      udp: true               # 启用udp
      udp-over-tcp: false     # 启用 UDP over TCP
      skip-cert-verify: false # 跳过证书验证

###########################################################################################################################
proxy-groups:
  - name: ♻️自动选择    # 策略组名字，不要重复
    type: url-test     # 策略组类型
    use:
      - main
      - backup
    url: http://www.gstatic.com/generate_204  # 健康检查地址
    interval: 30       # 健康检查间隔
    tolerance: 200     # url-test切换阈值
    lazy: true         # 懒惰状态，未选择到当前策略组时，不进行测试
    timeout: 5000      # 健康检查超时时间，单位为毫秒
  
  - name: 🐟漏网之鱼
    type: select
    proxies:
      - DIRECT
      - ♻️自动选择
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇸🇬狮城节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换
  
  - name: 🖐️手动切换
    type: select
    use:
      - main
      - backup
  
  - name: Ⓜ️微软Bing
    type: select
    proxies:
      - ⚠️自动回退
      - ♻️自动选择
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇸🇬狮城节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换
      - DIRECT
  
  - name: 🤖OpenAi
    type: select
    proxies:
      - 🇸🇬狮城节点
      - ♻️自动选择
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换
  
  - name: 📞电报消息
    type: select
    proxies:
      - ♻️自动选择
      - 🇭🇰香港节点
      - 🇨🇳台湾节点
      - 🇸🇬狮城节点
      - 🇯🇵日本节点
      - 🇺🇲美国节点
      - 🖐️手动切换
  
  - name: ⚠️自动回退
    type: fallback
    use:
      - main
      - backup
    url: http://www.gstatic.com/generate_204  # 健康检查地址
    interval: 30       # 健康检查间隔
    lazy: true         # 懒惰状态，未选择到当前策略组时，不进行测试
    timeout: 5000      # 健康检查超时时间，单位为毫
  
  - name: 🇭🇰香港节点
    type: url-test
    use:
      - main
      - backup
    url: http://www.gstatic.com/generate_204  # 健康检查地址
    interval: 30       # 健康检查间隔
    tolerance: 200     # url-test切换阈值
    lazy: true         # 懒惰状态，未选择到当前策略组时，不进行测试
    timeout: 5000      # 健康检查超时时间，单位为毫
    filter: "港|HK|hk|Hong Kong|HongKong|hongkong"
  
  - name: 🇯🇵日本节点
    type: url-test
    use:
      - main
      - backup
    url: http://www.gstatic.com/generate_204  # 健康检查地址
    interval: 30       # 健康检查间隔
    tolerance: 200     # url-test切换阈值
    lazy: true         # 懒惰状态，未选择到当前策略组时，不进行测试
    timeout: 5000      # 健康检查超时时间，单位为毫
    filter: "日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan"
  
  - name: 🇺🇲美国节点
    type: url-test
    use:
      - main
      - backup
    url: http://www.gstatic.com/generate_204  # 健康检查地址
    interval: 30       # 健康检查间隔
    tolerance: 200     # url-test切换阈值
    lazy: true         # 懒惰状态，未选择到当前策略组时，不进行测试
    timeout: 5000      # 健康检查超时时间，单位为毫
    filter: "美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"
  
  - name: 🇨🇳台湾节点
    type: url-test
    use:
      - main
      - backup
    url: http://www.gstatic.com/generate_204  # 健康检查地址
    interval: 30       # 健康检查间隔
    tolerance: 200     # url-test切换阈值
    lazy: true         # 懒惰状态，未选择到当前策略组时，不进行测试
    timeout: 5000      # 健康检查超时时间，单位为毫
    filter: "台|新北|彰化|TW|Taiwan"
  
  - name: 🇸🇬狮城节点
    type: url-test
    use:
      - main
      - backup
    url: http://www.gstatic.com/generate_204  # 健康检查地址
    interval: 30       # 健康检查间隔
    tolerance: 200     # url-test切换阈值
    lazy: true         # 懒惰状态，未选择到当前策略组时，不进行测试
    timeout: 5000      # 健康检查超时时间，单位为毫
    filter: "新加坡|坡|狮城|SG|Singapore"

###########################################################################################################################
rule-providers:  
  ♻️自动选择-FISH:
    type: http
    behavior: classical
    url: https://sub.xeton.dev/getruleset?type=6&url=
    path: ./providers/rule-provider_♻️自动选择-FISH.yaml
    interval: 86400
  
  🌐Direct-FISH:
    type: http
    behavior: classical
    url: https://sub.xeton.dev/getruleset?type=6&url=
    path: ./providers/rule-provider_🌐Direct-FISH.yaml
    interval: 86400
  
  UnBan:
    type: http
    behavior: classical
    url: https://sub.xeton.dev/getruleset?type=6&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9yZWZzL2hlYWRzL21hc3Rlci9DbGFzaC9VbkJhbi5saXN0
    path: ./providers/rule-provider_UnBan.yaml
    interval: 86400
  
  Download:
    type: http
    behavior: classical
    url: https://sub.xeton.dev/getruleset?type=6&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9yZWZzL2hlYWRzL21hc3Rlci9DbGFzaC9Eb3dubG9hZC5saXN0
    path: ./providers/rule-provider_Download.yaml
    interval: 86400
  
  GoogleCN:
    type: http
    behavior: classical
    url: https://sub.xeton.dev/getruleset?type=6&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9yZWZzL2hlYWRzL21hc3Rlci9DbGFzaC9SdWxlc2V0L0dvb2dsZUNOLmxpc3Q
    path: ./providers/rule-provider_GoogleCN.yaml
    interval: 86400
  
  Bing:
    type: http
    behavior: classical
    url: https://sub.xeton.dev/getruleset?type=6&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9yZWZzL2hlYWRzL21hc3Rlci9DbGFzaC9CaW5nLmxpc3Q
    path: ./providers/rule-provider_Bing.yaml
    interval: 86400
  
  Microsoft:
    type: http
    behavior: classical
    url: https://sub.xeton.dev/getruleset?type=6&url=aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FDTDRTU1IvQUNMNFNTUi9yZWZzL2hlYWRzL21hc3Rlci9DbGFzaC9NaWNyb3NvZnQubGlzdA
    path: ./providers/rule-provider_Microsoft.yaml
    interval: 86400

###########################################################################################################################
rules:
  - DOMAIN,portal.office.com,🇭🇰香港节点
  - DOMAIN-SUFFIX,asmrbbs.com,🇭🇰香港节点
  - RULE-SET,♻️自动选择-FISH,♻️自动选择
  - RULE-SET,🌐Direct-FISH,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  - GEOSITE,private,DIRECT
  - RULE-SET,UnBan,DIRECT
  - GEOSITE,category-ads-all,REJECT
  - RULE-SET,Download,DIRECT
  - RULE-SET,GoogleCN,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - RULE-SET,Bing,Ⓜ️微软Bing
  - GEOSITE,onedrive,DIRECT
  - RULE-SET,Microsoft,DIRECT
  - GEOSITE,openai,🤖OpenAi
  - GEOSITE,bahamut,🇨🇳台湾节点
  - GEOSITE,telegram,📞电报消息
  - GEOIP,telegram,📞电报消息,no-resolve
  - GEOSITE,category-porn,♻️自动选择
  - GEOSITE,gfw,♻️自动选择
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT,no-resolve
  - MATCH,🐟漏网之鱼
```
