### ISSUE TITLE
希望增加 TCP 使用 TPROXY，UDP 使用 TUN

### ISSUE THREAD

**Issue by Mikihta** [morytyann/OpenWrt-mihomo#70]
在配置文件过程中遇到直连 IPV6 的 UDP 流量时，tproxy 端口引起的回环访问
![屏幕截图 2024-08-15 211419](https://github.com/user-attachments/assets/74fc1666-b8c1-4186-bb3d-1f8be4efb03d)
（技术小白，不太理解这代表了什么，但引起了本该直连的网络加载缓慢甚至断联）
在使用TUN模式下没有这个问题，但由于 TUN 模式下网速减少约30%(可能是因为路由器性能不足，路由器为GL iNet MT3000）

**Comment by morytyann** [comment]
配置一下`代理配置 -> 绕过 -> Wan6 接口`，应该可以解决这个问题

**Comment by Mikihta** [comment]
在配置保存后后关闭并重新打开插件，问题依然存在
![屏幕截图 2024-08-15 212841](https://github.com/user-attachments/assets/f5046c37-c537-4a15-b948-0067751e7513)
打开 iOS 端哔哩哔哩依然有大量警告

**Comment by Mikihta** [comment]
附上配置文件

**Comment by morytyann** [comment]
运行`nft list set inet mihomo wan_ip6`看下结果，可能是没有获取到IPv6前缀导致的

**Comment by Mikihta** [comment]
附上配置
```YAML
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
Aport: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
profile:
  tracing: true
dns:
  enable: true
  listen: 127.0.0.1:8853
  default-nameserver:
    - tls://1.1.1.1/dns-query
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - https://dns.cloudflare.com/dns-query?
    - https://dns.google/dns-query?
  nameserver-policy:
    'mail1.9wan.win': system
    'geosite:geolocation-!cn': [tls://8.8.4.4, https://1.0.0.1/dns-query]
    'rule-set:Rule_Google,Rule_GoogleFCM,Rule_Microsoft,Rule_Bing,Rule_Copilot,Rule_Xbox,Rule_GameDownloadCN,Rule_Cloudflarecn': [tls://8.8.4.4, https://1.1.1.1/dns-query]
    'geosite:cn': [tls://223.5.5.5/dns-query,tls://1.12.12.12/dns-query,https://1.12.12.12/dns-query]
    'rule-set:Rule_ChinaMax': [tls://223.5.5.5/dns-query,tls://1.12.12.12/dns-query,https://1.12.12.12/dns-query]
proxies:

proxy-providers:
  Unicorn:
    type: http
    url: "https://mail1.9wan.win/api/v1/client/subscribe?token=6bf1ef4431885e8c67ae4dfd0a7958a1"
    path: ./Providers_Proxy/Unicorn.yaml
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      expected-status: 204
    filter: "ˣ¹"

  
  UnicornLite:
    type: http
    url: ""
    path: ./Providers_Proxy/UnicornLite.yaml
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      expected-status: 204
    exclude-filter: "网址|新加坡|香港|日本|美国|台湾|韩国"
    
  
  UnicornIPLC:
    type: http
    url: ""
    path: ./Providers_Proxy/UnicornIPLC.yaml
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      expected-status: 204
    filter: "ˣ⁵"

proxy-groups:
# 代理
- name: 默认代理
  type: select
  proxies:
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite

# 分流
- name: 境内网络
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Apple
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Google
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Microsoft
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Binance
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Bing
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Bitwarden
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Cloudflare
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Discord
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Docker
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Figma
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: GitHub
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Instagram
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Minecraft
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Notion
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: OpenAI
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: PayPal
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: PicACG
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: PikPak
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite  
- name: Pixiv
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Reddit
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Rutraker
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Sky
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Speedtest
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Spotify
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Telegram
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: TikTok
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: 𝕏(Twitter)
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: YouTube
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: Z-Library
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: 游戏网络
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: 游戏下载
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: PT下载
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: 广告
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: ❮Tailscale❯
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: ❮Mihomo❯
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite
- name: 未匹配
  type: select
  proxies:
    - 默认代理
    - DIRECT
    - REJECT
    - PASS
    - 「香港」
    - 「台湾」
    - 「狮城」
    - 「日本」
    - 「美国」
  use: 
  - UnicornIPLC
  - UnicornLite

# 国家
- name: 「香港」
  type: url-test
  use:
    - Unicorn
  url: "https://www.gstatic.com/generate_204"
  interval: 300
  filter: "HK"
  hidden: true

- name: 「台湾」
  type: url-test
  use:
    - Unicorn
  url: "https://www.gstatic.com/generate_204"
  interval: 300
  filter: "TW"
  hidden: true

- name: 「狮城」
  type: url-test
  use:
    - Unicorn
  url: "https://www.gstatic.com/generate_204"
  interval: 300
  filter: "SG"
  hidden: true

- name: 「日本」
  type: url-test
  use:
    - Unicorn
  url: "https://www.gstatic.com/generate_204"
  interval: 300
  filter: "JP"
  hidden: true

- name: 「美国」
  type: url-test
  use:
    - Unicorn
  url: "https://www.gstatic.com/generate_204"
  interval: 300
  filter: "US"
  hidden: true

rules:
  - PROCESS-NAME,mihomo,❮Mihomo❯
  - PROCESS-NAME,tailscaled,❮Tailscale❯
  - SUB-RULE,(RULE-SET,Rule_AdG),sub-rule-AdG
  - RULE-SET,Rule_Ad,广告
  - RULE-SET,Rule_PikPak_Chk,广告
  - RULE-SET,Rule_Hijack⁺,广告
  - RULE-SET,Rule_Apple,Apple
  - RULE-SET,Rule_Beats,Apple
  - RULE-SET,Rule_AppleID,Apple
  - RULE-SET,Rule_AppleDev,Apple
  - RULE-SET,Rule_SystemOTA,Apple
  - RULE-SET,Rule_Google,Google
  - RULE-SET,Rule_GoogleFCM,Google
  - RULE-SET,Rule_BardAI,Google
  - RULE-SET,Rule_Gemini,Google 
  - RULE-SET,Rule_OpenAI,OpenAI
  - RULE-SET,Rule_Copilot,Bing
  - RULE-SET,Rule_Bing,Bing
  - RULE-SET,Rule_Microsoft,Microsoft
  - RULE-SET,Rule_Xbox,Microsoft
  - RULE-SET,Rule_Binance,Binance
  - DOMAIN-SUFFIX,binance.info,Binance
  - RULE-SET,Rule_Bitwarden,Bitwarden
  - RULE-SET,Rule_Discord,Discord
  - RULE-SET,Rule_Docker,Docker
  - RULE-SET,Rule_Figma,Figma
  - RULE-SET,Rule_GitHub,GitHub
  - RULE-SET,Rule_Instagram,Instagram
  - RULE-SET,Rule_Mojang,Minecraft
  - RULE-SET,Rule_Notion,Notion
  - RULE-SET,Rule_PayPal,PayPal
  - RULE-SET,Rule_Picacg,PicACG
  - RULE-SET,Rule_PikPak,PikPak
  - RULE-SET,Rule_Pixiv,Pixiv
  - RULE-SET,Rule_Reddit,Reddit
  - RULE-SET,Rule_Rutraker,Rutraker
  - RULE-SET,Rule_Spotify,Spotify
  - RULE-SET,Rule_Telegram,Telegram
  - RULE-SET,Rule_TikTok,TikTok
  - RULE-SET,Rule_Twitter,𝕏(Twitter)
  - RULE-SET,Rule_YouTubeMusic,YouTube
  - RULE-SET,Rule_YouTube,YouTube
  - RULE-SET,Rule_z-library,Z-Library
  - RULE-SET,Rule_Cloudflarecn,Cloudflare
  - RULE-SET,Rule_Cloudflare,Cloudflare
  - RULE-SET,Rule_Speedtest,Speedtest
  - RULE-SET,Rule_GameDownloadCN,游戏下载
  - RULE-SET,Rule_GameDownload,游戏下载
  - RULE-SET,Rule_SteamCN⁺,游戏下载
  - RULE-SET,Rule_Game,游戏网络
  - DOMAIN,stream.starwatch.ai,Sky
  - DOMAIN-SUFFIX,thatgamecompany.com,Sky
  - AND,((IP-ASN,16509),(NETWORK,UDP)),Sky
  - RULE-SET,Rule_PrivateTracke,PT下载
  - RULE-SET,Rule_Proxy,默认代理
  - RULE-SET,Rule_ChinaMax,境内网络
  - MATCH,未匹配
sub-rules:
  sub-rule-AdG:
    - NOT,((RULE-SET,Rule_AdG_Direct)),广告
rule-providers:
  Rule_Apple:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.list
    path: ./Providers_Rule/Apple.list
    interval: 86400
    format: text

  Rule_Beats:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Beats/Beats.list
    path: ./Providers_Rule/Beats.list
    interval: 86400
    format: text

  Rule_AppleID:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AppleID/AppleID.list
    path: ./Providers_Rule/AppleID.list
    interval: 86400
    format: text

  Rule_AppleDev:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AppleDev/AppleDev.list
    path: ./Providers_Rule/AppleDev.list
    interval: 86400
    format: text

  Rule_SystemOTA:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SystemOTA/SystemOTA.list
    path: ./Providers_Rule/SystemOTA.list
    interval: 86400
    format: text

  Rule_Google:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.list
    path: ./Providers_Rule/Google.list
    interval: 86400
    format: text

  Rule_GoogleFCM:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleFCM/GoogleFCM.list
    path: ./Providers_Rule/GoogleFCM.list
    interval: 86400
    format: text

  Rule_BardAI:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BardAI/BardAI.list
    path: ./Providers_Rule/BardAI.list
    interval: 86400
    format: text

  Rule_Gemini:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.list
    path: ./Providers_Rule/Gemini.list
    interval: 86400
    format: text

  Rule_Microsoft:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.list
    path: ./Providers_Rule/Microsoft.list
    interval: 86400
    format: text

  Rule_Xbox:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Xbox/Xbox.list
    path: ./Providers_Rule/Xbox.list
    interval: 86400
    format: text

  Rule_Binance:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Binance/Binance.list
    path: ./Providers_Rule/Binance.list
    interval: 86400
    format: text

  Rule_Copilot:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.list
    path: ./Providers_Rule/Copilot.list
    interval: 86400
    format: text

  Rule_Bing:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.list
    path: ./Providers_Rule/Bing.list
    interval: 86400
    format: text

  Rule_Bitwarden:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Mikihta/Rule@main/Ruleset/Bitwarden.list
    path: ./Providers_Rule/Bitwarden.list
    interval: 86400
    format: text

  Rule_Cloudflarecn:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflarecn/Cloudflarecn.list
    path: ./Providers_Rule/Cloudflarecn.list
    interval: 86400
    format: text

  Rule_Cloudflare:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflare/Cloudflare.list
    path: ./Providers_Rule/Cloudflare.list
    interval: 86400
    format: text

  Rule_Discord:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Discord/Discord.list
    path: ./Providers_Rule/Discord.list
    interval: 86400
    format: text

  Rule_Docker:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Docker/Docker.list
    path: ./Providers_Rule/Docker.list
    interval: 86400
    format: text

  Rule_Figma:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Figma/Figma.list
    path: ./Providers_Rule/Figma.list
    interval: 86400
    format: text

  Rule_GitHub:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.list
    path: ./Providers_Rule/GitHub.list
    interval: 86400
    format: text

  Rule_Instagram:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Instagram/Instagram.list
    path: ./Providers_Rule/Instagram.list
    interval: 86400
    format: text

  Rule_Mojang:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Mikihta/Rule@main/Ruleset/Mojang.list
    path: ./Providers_Rule/Mojang.list
    interval: 86400
    format: text

  Rule_Notion:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Notion/Notion.list
    path: ./Providers_Rule/Notion.list
    interval: 86400
    format: text

  Rule_OpenAI:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.list
    path: ./Providers_Rule/OpenAI.list
    interval: 86400
    format: text

  Rule_PayPal:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PayPal/PayPal.list
    path: ./Providers_Rule/PayPal.list
    interval: 86400
    format: text

  Rule_Picacg:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Picacg/Picacg.list
    path: ./Providers_Rule/Picacg.list
    interval: 86400
    format: text

  Rule_Reddit:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Reddit/Reddit.list
    path: ./Providers_Rule/Reddit.list
    interval: 86400
    format: text

  Rule_Rutraker:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Mikihta/Rule@main/Ruleset/Rutraker.list
    path: ./Providers_Rule/Rutraker.list
    interval: 86400
    format: text

  Rule_Speedtest:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Speedtest/Speedtest.list
    path: ./Providers_Rule/Speedtest.list
    interval: 86400
    format: text

  Rule_Spotify:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.list
    path: ./Providers_Rule/Spotify.list
    interval: 86400
    format: text

  Rule_Telegram:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.list
    path: ./Providers_Rule/Telegram.list
    interval: 86400
    format: text

  Rule_TikTok:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.list
    path: ./Providers_Rule/TikTok.list
    interval: 86400
    format: text

  Rule_Twitter:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.list
    path: ./Providers_Rule/Twitter.list
    interval: 86400
    format: text

  Rule_YouTubeMusic:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTubeMusic/YouTubeMusic.list
    path: ./Providers_Rule/YouTubeMusic.list
    interval: 86400
    format: text

  Rule_YouTube:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.list
    path: ./Providers_Rule/YouTube.list
    interval: 86400
    format: text

  Rule_z-library:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Mikihta/Rule@main/Ruleset/z-library.list
    path: ./Providers_Rule/z-library.list
    interval: 86400
    format: text

  Rule_Game:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.list
    path: ./Providers_Rule/Game.list
    interval: 86400
    format: text

  Rule_GameDownloadCN:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
    path: ./Providers_Rule/GameDownloadCN.list
    interval: 86400
    format: text

  Rule_GameDownload:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload.list
    path: ./Providers_Rule/GameDownload.list
    interval: 86400
    format: text

  Rule_PrivateTracke:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.list
    path: ./Providers_Rule/PrivateTracke.list
    interval: 86400
    format: text

  Rule_Proxy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy.list
    path: ./Providers_Rule/Proxy.list
    interval: 86400
    format: text
  Rule_ChinaMax:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax.list
    path: ./Providers_Rule/ChinaMax.list
    interval: 86400
    format: text
  Rule_Ad:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising.list
    path: ./Providers_Rule/Ad.list
    interval: 86400
    format: text
  Rule_AdG:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter.list
    path: ./Providers_Rule/AdG.list
    interval: 86400
    format: text
  Rule_AdG_Direct:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdGuardSDNSFilter/Direct/Direct.list
    path: ./Providers_Rule/AdG_Direct.list
    interval: 86400
    format: text
  Rule_Hijack⁺:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Mikihta/Rule@main/Ruleset/Hijack%E2%81%BA.list
    path: ./Providers_Rule/Hijack⁺.list
    interval: 86400
    format: text
  Rule_SteamCN⁺:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Mikihta/Rule@main/Ruleset/SteamCN%E2%81%BA.list
    path: ./Providers_Rule/SteamCN⁺.list
    interval: 86400
    format: text
  Rule_PikPak_Chk:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Mikihta/Rule@main/Ruleset/PikPak_Chk.list
    path: ./Providers_Rule/PikPak_Chk.list
    interval: 86400
    format: text
  Rule_PikPak:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PikPak/PikPak.list
    path: ./Providers_Rule/PikPak.list
    interval: 86400
    format: text
  Rule_Pixiv:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Pixiv/Pixiv.list
    path: ./Providers_Rule/Pixiv.list
    interval: 86400
    format: text
```
